spring.application.name=whatsapp-brain-service
server.port=8080

# Core Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/replato
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Keycloak Administration Connection Properties
keycloak.server-url=http://localhost:8180
keycloak.realm=replato-gateway
keycloak.username=admin
keycloak.password=admin
